language: python

python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_script:
  - "pip install -r requirements_dev.txt"
  - "pip install -r requirements.txt"

script: python -m phulpy test
